name: Snyk Example

on:
  push:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Snyk
      uses: snyk/actions/setup@v2

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.13'

    - name: Snyk test
      run: snyk test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
